### ISSUE TITLE
Docs Cleanup 4/25

### ISSUE THREAD

**Issue by htroisi** [pixie-labs/pixie-docs#29]
- [ ] Add social buttons to header: https://github.com/pixie-labs/pixie-docs/issues/26
- [ ] Window resizing bug: https://github.com/pixie-labs/pixie-docs/issues/2
- [ ] Search box is broken on mobile: https://github.com/pixie-labs/pixie-docs/issues/17
- [ ] Make Python API functions searchable: https://github.com/pixie-labs/pixie-docs/issues/5
- [ ] Code block Line numbers: https://github.com/pixie-labs/pixie-docs/issues/9 
- [ ] Use code syntax styling in material alerts: https://github.com/pixie-labs/pixie-docs/issues/8
